
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 09 11:28:34 CET 2022
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;

/** CUP v0.10k generated parser.
  * @version Sun Jan 09 11:28:34 CET 2022
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\047\000\002\003\006\000\002\002\004\000\002\004" +
    "\006\000\002\005\004\000\002\005\003\000\002\007\005" +
    "\000\002\011\005\000\002\011\003\000\002\012\004\000" +
    "\002\013\004\000\002\013\002\000\002\014\005\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\006" +
    "\004\000\002\006\003\000\002\015\012\000\002\015\006" +
    "\000\002\015\007\000\002\015\007\000\002\015\003\000" +
    "\002\017\005\000\002\017\005\000\002\017\003\000\002" +
    "\022\005\000\002\022\005\000\002\022\003\000\002\023" +
    "\003\000\002\023\003\000\002\023\005\000\002\016\004" +
    "\000\002\024\004\000\002\024\002\000\002\025\005\000" +
    "\002\020\005\000\002\020\003\000\002\021\005\000\002" +
    "\021\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\120\000\004\004\005\001\002\000\004\002\122\001" +
    "\002\000\004\025\006\001\002\000\004\026\007\001\002" +
    "\000\004\031\010\001\002\000\010\005\012\006\016\007" +
    "\017\001\002\000\004\002\001\001\002\000\004\020\ufff5" +
    "\001\002\000\022\005\012\006\016\007\017\010\033\011" +
    "\043\012\036\020\042\031\010\001\002\000\004\020\021" +
    "\001\002\000\022\005\ufffd\006\ufffd\007\ufffd\010\ufffd\011" +
    "\ufffd\012\ufffd\020\ufffd\031\ufffd\001\002\000\004\020\ufff4" +
    "\001\002\000\004\020\ufff3\001\002\000\006\022\ufffa\023" +
    "\ufffa\001\002\000\010\022\ufff7\023\ufff7\027\ufff7\001\002" +
    "\000\006\022\024\023\023\001\002\000\004\020\021\001" +
    "\002\000\022\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011\ufffc" +
    "\012\ufffc\020\ufffc\031\ufffc\001\002\000\006\022\ufffb\023" +
    "\ufffb\001\002\000\010\022\ufff9\023\ufff9\027\030\001\002" +
    "\000\010\022\ufff8\023\ufff8\027\ufff8\001\002\000\004\021" +
    "\031\001\002\000\004\030\032\001\002\000\010\022\ufff6" +
    "\023\ufff6\027\ufff6\001\002\000\004\025\113\001\002\000" +
    "\004\024\110\001\002\000\016\010\uffec\011\uffec\012\uffec" +
    "\020\uffec\031\uffec\032\uffec\001\002\000\004\025\101\001" +
    "\002\000\016\010\033\011\043\012\036\020\042\031\010" +
    "\032\100\001\002\000\022\005\ufffe\006\ufffe\007\ufffe\010" +
    "\ufffe\011\ufffe\012\ufffe\020\ufffe\031\ufffe\001\002\000\016" +
    "\010\ufff1\011\ufff1\012\ufff1\020\ufff1\031\ufff1\032\ufff1\001" +
    "\002\000\026\014\uffe0\015\uffe0\016\uffe0\017\uffe0\022\uffe0" +
    "\023\uffe0\024\uffe0\026\uffe0\027\uffe0\030\uffe0\001\002\000" +
    "\004\025\044\001\002\000\010\020\042\021\045\025\053" +
    "\001\002\000\022\014\uffe4\015\uffe4\016\uffe4\017\uffe4\022" +
    "\uffe4\023\uffe4\026\uffe4\030\uffe4\001\002\000\022\014\uffe6" +
    "\015\uffe6\016\uffe6\017\uffe6\022\uffe6\023\uffe6\026\uffe6\030" +
    "\uffe6\001\002\000\022\014\uffe9\015\uffe9\016\061\017\062" +
    "\022\uffe9\023\uffe9\026\uffe9\030\uffe9\001\002\000\022\014" +
    "\uffe5\015\uffe5\016\uffe5\017\uffe5\022\uffe5\023\uffe5\026\uffe5" +
    "\030\uffe5\001\002\000\012\014\057\015\056\023\uffdb\026" +
    "\uffdb\001\002\000\006\023\066\026\067\001\002\000\010" +
    "\020\042\021\045\025\053\001\002\000\010\014\057\015" +
    "\056\026\055\001\002\000\022\014\uffe3\015\uffe3\016\uffe3" +
    "\017\uffe3\022\uffe3\023\uffe3\026\uffe3\030\uffe3\001\002\000" +
    "\010\020\042\021\045\025\053\001\002\000\010\020\042" +
    "\021\045\025\053\001\002\000\022\014\uffeb\015\uffeb\016" +
    "\061\017\062\022\uffeb\023\uffeb\026\uffeb\030\uffeb\001\002" +
    "\000\010\020\042\021\045\025\053\001\002\000\010\020" +
    "\042\021\045\025\053\001\002\000\022\014\uffe7\015\uffe7" +
    "\016\uffe7\017\uffe7\022\uffe7\023\uffe7\026\uffe7\030\uffe7\001" +
    "\002\000\022\014\uffe8\015\uffe8\016\uffe8\017\uffe8\022\uffe8" +
    "\023\uffe8\026\uffe8\030\uffe8\001\002\000\022\014\uffea\015" +
    "\uffea\016\061\017\062\022\uffea\023\uffea\026\uffea\030\uffea" +
    "\001\002\000\010\020\042\021\045\025\053\001\002\000" +
    "\004\022\070\001\002\000\016\010\uffed\011\uffed\012\uffed" +
    "\020\uffed\031\uffed\032\uffed\001\002\000\012\014\057\015" +
    "\056\023\uffdc\026\uffdc\001\002\000\026\014\uffe2\015\uffe2" +
    "\016\uffe2\017\uffe2\022\uffe2\023\uffe2\024\uffe2\026\uffe2\027" +
    "\074\030\uffe2\001\002\000\026\014\uffe1\015\uffe1\016\uffe1" +
    "\017\uffe1\022\uffe1\023\uffe1\024\uffe1\026\uffe1\027\uffe1\030" +
    "\uffe1\001\002\000\010\020\042\021\045\025\053\001\002" +
    "\000\010\014\057\015\056\030\076\001\002\000\026\014" +
    "\uffdf\015\uffdf\016\uffdf\017\uffdf\022\uffdf\023\uffdf\024\uffdf" +
    "\026\uffdf\027\uffdf\030\uffdf\001\002\000\016\010\ufff2\011" +
    "\ufff2\012\ufff2\020\ufff2\031\ufff2\032\ufff2\001\002\000\020" +
    "\002\uffff\010\uffff\011\uffff\012\uffff\020\uffff\031\uffff\032" +
    "\uffff\001\002\000\010\005\012\006\016\007\017\001\002" +
    "\000\004\020\103\001\002\000\004\013\104\001\002\000" +
    "\004\020\105\001\002\000\004\026\106\001\002\000\014" +
    "\010\033\011\043\012\036\020\042\031\010\001\002\000" +
    "\016\010\ufff0\011\ufff0\012\ufff0\020\ufff0\031\ufff0\032\ufff0" +
    "\001\002\000\010\020\042\021\045\025\053\001\002\000" +
    "\010\014\057\015\056\022\112\001\002\000\016\010\uffef" +
    "\011\uffef\012\uffef\020\uffef\031\uffef\032\uffef\001\002\000" +
    "\004\020\042\001\002\000\006\023\uffdd\026\uffdd\001\002" +
    "\000\006\023\116\026\117\001\002\000\004\020\042\001" +
    "\002\000\004\022\120\001\002\000\016\010\uffee\011\uffee" +
    "\012\uffee\020\uffee\031\uffee\032\uffee\001\002\000\006\023" +
    "\uffde\026\uffde\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\120\000\004\003\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\004\010\001\001" +
    "\000\010\005\012\007\014\010\013\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\004\034\006\036\007\037" +
    "\010\013\015\040\016\033\001\001\000\006\011\021\012" +
    "\017\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\025\001\001\000" +
    "\002\001\001\000\004\012\024\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\014\026\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\004\034\015\076\016\033\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\024\071\001" +
    "\001\000\002\001\001\000\014\016\047\017\050\021\051" +
    "\022\046\023\045\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\016\047\017\053\022\046\023" +
    "\045\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\016\047\022\064\023\045\001\001\000\010\016\047\022" +
    "\057\023\045\001\001\000\002\001\001\000\006\016\047" +
    "\023\063\001\001\000\006\016\047\023\062\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\016\047\017\070\022\046\023\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\025\072" +
    "\001\001\000\002\001\001\000\012\016\047\017\074\022" +
    "\046\023\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\010\101\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\004\034\015\106\016\033\001" +
    "\001\000\002\001\001\000\012\016\047\017\110\022\046" +
    "\023\045\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\016\113\020\114\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\120\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



   
   public static void main( String[] args ) {
      try {
		   FileReader file = new FileReader( args[0] );
		   Scanner scanner = new Lexer( file );
		   Parser parser = new Parser( scanner );
		   parser.debug_parse();
	  }
	  catch( Exception e ) {
		   System.out.println(e);
	  }
   }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // ExpressionList ::= Expression 
            {
              Object RESULT = null;
		
              System.out.println( "Redukcija po smeni 38." );
           
              CUP$Parser$result = new java_cup.runtime.Symbol(15/*ExpressionList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // ExpressionList ::= ExpressionList COMMA Expression 
            {
              Object RESULT = null;
		
              System.out.println( "Redukcija po smeni 37." );
           
              CUP$Parser$result = new java_cup.runtime.Symbol(15/*ExpressionList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // VarList ::= Variable 
            {
              Object RESULT = null;
		
             System.out.println( "Redukcija po smeni 36." );
          
              CUP$Parser$result = new java_cup.runtime.Symbol(14/*VarList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // VarList ::= VarList COMMA Variable 
            {
              Object RESULT = null;
		
             System.out.println( "Redukcija po smeni 35." );
          
              CUP$Parser$result = new java_cup.runtime.Symbol(14/*VarList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Index ::= LEFTBOX Expression RIGHTBOX 
            {
              Object RESULT = null;
		
             System.out.println( "Redukcija po smeni 34." );
          
              CUP$Parser$result = new java_cup.runtime.Symbol(19/*Index*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // IndexList ::= 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 33." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(18/*IndexList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // IndexList ::= IndexList Index 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 32." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(18/*IndexList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // Variable ::= ID IndexList 
            {
              Object RESULT = null;
		
            System.out.println( "Redukcija po smeni 31." );
         
              CUP$Parser$result = new java_cup.runtime.Symbol(12/*Variable*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // Factor ::= LEFTPAR Expression RIGHTPAR 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 30." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*Factor*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // Factor ::= CONST 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 29." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*Factor*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // Factor ::= Variable 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 28." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(17/*Factor*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // Term ::= Factor 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 27." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(16/*Term*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // Term ::= Term DIV Factor 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 26." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(16/*Term*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Term ::= Term MUL Factor 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 25." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(16/*Term*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Expression ::= Term 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 24." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(13/*Expression*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // Expression ::= Expression SUB Term 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 23." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(13/*Expression*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // Expression ::= Expression PLUS Term 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 22." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(13/*Expression*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // Statement ::= Block 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 21." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(11/*Statement*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Statement ::= WRITE LEFTPAR ExpressionList RIGHTPAR SEMI 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 20." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(11/*Statement*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Statement ::= READ LEFTPAR VarList RIGHTPAR SEMI 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 19." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(11/*Statement*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Statement ::= Variable ASSIGN Expression SEMI 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 18." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(11/*Statement*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Statement ::= FOR LEFTPAR Type ID IN ID RIGHTPAR Statement 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 17." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(11/*Statement*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // StatementList ::= Statement 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 16." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(4/*StatementList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // StatementList ::= StatementList Statement 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 15." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(4/*StatementList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Type ::= CHAR 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 14." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Type ::= REAL 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 13." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Type ::= INTEGER 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 12." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(6/*Type*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Dimenssion ::= LEFTBOX CONST RIGHTBOX 
            {
              Object RESULT = null;
		
           System.out.println( "Redukcija po smeni 11." );
        
              CUP$Parser$result = new java_cup.runtime.Symbol(10/*Dimenssion*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // DimList ::= 
            {
              Object RESULT = null;
		
              System.out.println( "Redukcija po smeni 10." );
           
              CUP$Parser$result = new java_cup.runtime.Symbol(9/*DimList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // DimList ::= DimList Dimenssion 
            {
              Object RESULT = null;
		
              System.out.println( "Redukcija po smeni 9." );
           
              CUP$Parser$result = new java_cup.runtime.Symbol(9/*DimList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Name ::= ID DimList 
            {
              Object RESULT = null;
		
           System.out.println( "Redukcija po smeni 8." );
        
              CUP$Parser$result = new java_cup.runtime.Symbol(8/*Name*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NameList ::= Name 
            {
              Object RESULT = null;
		
                System.out.println( "Redukcija po smeni 7." );
             
              CUP$Parser$result = new java_cup.runtime.Symbol(7/*NameList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // NameList ::= NameList COMMA Name 
            {
              Object RESULT = null;
		
                System.out.println( "Redukcija po smeni 6." );
             
              CUP$Parser$result = new java_cup.runtime.Symbol(7/*NameList*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // VarDecl ::= Type NameList SEMI 
            {
              Object RESULT = null;
		
                   System.out.println( "Redukcija po smeni 5." );
                
              CUP$Parser$result = new java_cup.runtime.Symbol(5/*VarDecl*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // VarSection ::= VarDecl 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 4." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(3/*VarSection*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // VarSection ::= VarSection VarDecl 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 3." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(3/*VarSection*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // Block ::= LEFTBRACE VarSection StatementList RIGHTBRACE 
            {
              Object RESULT = null;
		
                System.out.println( "Redukcija po smeni 2." );
             
              CUP$Parser$result = new java_cup.runtime.Symbol(2/*Block*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= Program EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // Program ::= MAIN LEFTPAR RIGHTPAR Block 
            {
              Object RESULT = null;
		
               System.out.println( "Redukcija po smeni 1." );
            
              CUP$Parser$result = new java_cup.runtime.Symbol(1/*Program*/, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-0)).right, RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

