
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 17 11:13:41 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 6;
  public static final int LEFTBOX = 21;
  public static final int PLUS = 10;
  public static final int CHAR = 5;
  public static final int SEMI = 16;
  public static final int IN = 9;
  public static final int LEFTPAR = 19;
  public static final int RIGHTBOX = 22;
  public static final int RIGHTPAR = 20;
  public static final int WRITE = 7;
  public static final int ID = 14;
  public static final int SUB = 11;
  public static final int COMMA = 17;
  public static final int EOF = 0;
  public static final int MAIN = 2;
  public static final int DIV = 13;
  public static final int CONST = 15;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int INTEGER = 3;
  public static final int FOR = 8;
  public static final int RIGHTBRACE = 24;
  public static final int LEFTBRACE = 23;
  public static final int REAL = 4;
  public static final int MUL = 12;
}

